# Generated by Django 2.0 on 2019-01-08 18:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
                ('book1', django.db.models.manager.Manager()),
            ],
        ),
    ]
