# Generated by Django 2.0 on 2019-01-13 05:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_areainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinymceTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
